#!/bin/bash
# Setup password for borg 
# Creates a random password, stores the EA, stores in keychain.
# If you don't want to store the password in the JSS, comment out that section.

# Get logged in user
loggedInUser=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

# create a random password
borg_password=$(head -c 32 /dev/urandom | base64)

# add the randomly created password to the logged in user's keychain
#sudo -H -u ${loggedInUser} security add-generic-password -D secret -U -a ${loggedInUser} -s borg-passphrase -w ${borg_password}
security add-generic-password -D secret -U -a "${loggedInUser}" -s borg-passphrase -w "${borg_password}"
