#!/bin/bash
# borg init
# this script needs to be ran AS THE USER

#Determine logged in user
loggedInUser=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

# repo_server_address
repo_server_address=server.example.org

# Repo address
REPO=${loggedInUser}@${repo_server_address}:backups

# Grab the password from the logged in user's keychain.
export BORG_PASSCOMMAND="security find-generic-password -a ${loggedInUser} -s borg-passphrase -w"

# Initialize the borg repo on the backup server
borg init --encryption=repokey ${REPO}

